# Generated by Django 4.0.7 on 2022-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientAccountNo', models.IntegerField()),
                ('newCreditCustomer', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('amount', models.FloatField(blank=True)),
                ('interest', models.FloatField(blank=True)),
                ('loanDuration', models.IntegerField(blank=True)),
                ('monthlyPayment', models.FloatField(blank=True)),
                ('education', models.IntegerField()),
                ('maritalStatus', models.IntegerField()),
                ('employmentStatus', models.IntegerField()),
                ('employmentDurationCurrentEmployer', models.CharField(max_length=100)),
                ('incomeTotal', models.IntegerField()),
                ('debtToIncomeRatio', models.FloatField()),
                ('lossGivenDefault', models.FloatField(blank=True)),
                ('creditScore', models.FloatField()),
                ('noOfPreviousLoansBeforeLoan', models.IntegerField()),
                ('amountOfPreviousLoansBeforeLoan', models.IntegerField()),
                ('noOfPreviousEarlyRepaymentsBeforeLoan', models.IntegerField()),
                ('verdict', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
